---
layout: cv
title: Resume
---
# Bradley Jensen

Student at Brigham Young University - Idaho

## Education

Studying Data science at Brigham Young University - Idaho

## Experience

Voluntary Religious Missionary                                        August 2023 - August 2025
                                                                        Antananarivo, Madagascar
The Church of Jesus Christ of Latter Day Saints

 Established relationships within 5 communities and led religious efforts to teach principles of the 
Gospel of Jesus Christ
 Promoted positive relations with 1-3 coworkers from vast cultural and ethnic backgrounds in multiple 
shared house settings
 Supervised groups of 9-26 missionaries in day-to-day work to sustain effective use of time and 
obedience to missionary standards

Lot Attendant                                                              June 2023 - August 2023
                                                                                    Tempe, Arizona
Insight motors

 Coordinated with marketing department and transported 7-10 vehicles weekly to desired locations
 Maintained highest quality of cleanliness in 50+ vehicles held on lot
 Serviced vehicles with minor issues to ensure safe use and improved durability

Crew Member
                                                                                    Mesa, Arizona
Little Caesars

 Interacted with 4-5 coworkers in high-stress scenarios, fulfilling orders and ensuring high-quality 
product
 Managed cleanliness of store and ensured floors, counters, and equipment were sanitized
 Communicated needs of each station and insured 5 stations were run efficiently at all times

## Languages

 English(Native), Malagasy(Conversational)
 Profficient in Python, SQL, R

<!-- ### Footer

Last updated: May 2013 -->